// This file was generated by counterfeiter
package fakes

import (
	"net/http"
	"sync"

	"github.com/concourse/retryhttp"
)

type FakeHijackableClient struct {
	DoStub        func(req *http.Request) (*http.Response, retryhttp.HijackCloser, error)
	doMutex       sync.RWMutex
	doArgsForCall []struct {
		req *http.Request
	}
	doReturns struct {
		result1 *http.Response
		result2 retryhttp.HijackCloser
		result3 error
	}
}

func (fake *FakeHijackableClient) Do(req *http.Request) (*http.Response, retryhttp.HijackCloser, error) {
	fake.doMutex.Lock()
	fake.doArgsForCall = append(fake.doArgsForCall, struct {
		req *http.Request
	}{req})
	fake.doMutex.Unlock()
	if fake.DoStub != nil {
		return fake.DoStub(req)
	} else {
		return fake.doReturns.result1, fake.doReturns.result2, fake.doReturns.result3
	}
}

func (fake *FakeHijackableClient) DoCallCount() int {
	fake.doMutex.RLock()
	defer fake.doMutex.RUnlock()
	return len(fake.doArgsForCall)
}

func (fake *FakeHijackableClient) DoArgsForCall(i int) *http.Request {
	fake.doMutex.RLock()
	defer fake.doMutex.RUnlock()
	return fake.doArgsForCall[i].req
}

func (fake *FakeHijackableClient) DoReturns(result1 *http.Response, result2 retryhttp.HijackCloser, result3 error) {
	fake.DoStub = nil
	fake.doReturns = struct {
		result1 *http.Response
		result2 retryhttp.HijackCloser
		result3 error
	}{result1, result2, result3}
}

var _ retryhttp.HijackableClient = new(FakeHijackableClient)
