// Code generated by counterfeiter. DO NOT EDIT.
package retryhttpfakes

import (
	"sync"

	backoff "github.com/cenkalti/backoff/v5"
	"github.com/concourse/retryhttp"
)

type FakeBackOffFactory struct {
	NewBackOffStub        func() retryhttp.BackOff
	newBackOffMutex       sync.RWMutex
	newBackOffArgsForCall []struct {
	}
	newBackOffReturns struct {
		result1 retryhttp.BackOff
	}
	newBackOffReturnsOnCall map[int]struct {
		result1 retryhttp.BackOff
	}
	WithMaxElapsedTimeStub        func() backoff.RetryOption
	withMaxElapsedTimeMutex       sync.RWMutex
	withMaxElapsedTimeArgsForCall []struct {
	}
	withMaxElapsedTimeReturns struct {
		result1 backoff.RetryOption
	}
	withMaxElapsedTimeReturnsOnCall map[int]struct {
		result1 backoff.RetryOption
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBackOffFactory) NewBackOff() retryhttp.BackOff {
	fake.newBackOffMutex.Lock()
	ret, specificReturn := fake.newBackOffReturnsOnCall[len(fake.newBackOffArgsForCall)]
	fake.newBackOffArgsForCall = append(fake.newBackOffArgsForCall, struct {
	}{})
	stub := fake.NewBackOffStub
	fakeReturns := fake.newBackOffReturns
	fake.recordInvocation("NewBackOff", []interface{}{})
	fake.newBackOffMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBackOffFactory) NewBackOffCallCount() int {
	fake.newBackOffMutex.RLock()
	defer fake.newBackOffMutex.RUnlock()
	return len(fake.newBackOffArgsForCall)
}

func (fake *FakeBackOffFactory) NewBackOffCalls(stub func() retryhttp.BackOff) {
	fake.newBackOffMutex.Lock()
	defer fake.newBackOffMutex.Unlock()
	fake.NewBackOffStub = stub
}

func (fake *FakeBackOffFactory) NewBackOffReturns(result1 retryhttp.BackOff) {
	fake.newBackOffMutex.Lock()
	defer fake.newBackOffMutex.Unlock()
	fake.NewBackOffStub = nil
	fake.newBackOffReturns = struct {
		result1 retryhttp.BackOff
	}{result1}
}

func (fake *FakeBackOffFactory) NewBackOffReturnsOnCall(i int, result1 retryhttp.BackOff) {
	fake.newBackOffMutex.Lock()
	defer fake.newBackOffMutex.Unlock()
	fake.NewBackOffStub = nil
	if fake.newBackOffReturnsOnCall == nil {
		fake.newBackOffReturnsOnCall = make(map[int]struct {
			result1 retryhttp.BackOff
		})
	}
	fake.newBackOffReturnsOnCall[i] = struct {
		result1 retryhttp.BackOff
	}{result1}
}

func (fake *FakeBackOffFactory) WithMaxElapsedTime() backoff.RetryOption {
	fake.withMaxElapsedTimeMutex.Lock()
	ret, specificReturn := fake.withMaxElapsedTimeReturnsOnCall[len(fake.withMaxElapsedTimeArgsForCall)]
	fake.withMaxElapsedTimeArgsForCall = append(fake.withMaxElapsedTimeArgsForCall, struct {
	}{})
	stub := fake.WithMaxElapsedTimeStub
	fakeReturns := fake.withMaxElapsedTimeReturns
	fake.recordInvocation("WithMaxElapsedTime", []interface{}{})
	fake.withMaxElapsedTimeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBackOffFactory) WithMaxElapsedTimeCallCount() int {
	fake.withMaxElapsedTimeMutex.RLock()
	defer fake.withMaxElapsedTimeMutex.RUnlock()
	return len(fake.withMaxElapsedTimeArgsForCall)
}

func (fake *FakeBackOffFactory) WithMaxElapsedTimeCalls(stub func() backoff.RetryOption) {
	fake.withMaxElapsedTimeMutex.Lock()
	defer fake.withMaxElapsedTimeMutex.Unlock()
	fake.WithMaxElapsedTimeStub = stub
}

func (fake *FakeBackOffFactory) WithMaxElapsedTimeReturns(result1 backoff.RetryOption) {
	fake.withMaxElapsedTimeMutex.Lock()
	defer fake.withMaxElapsedTimeMutex.Unlock()
	fake.WithMaxElapsedTimeStub = nil
	fake.withMaxElapsedTimeReturns = struct {
		result1 backoff.RetryOption
	}{result1}
}

func (fake *FakeBackOffFactory) WithMaxElapsedTimeReturnsOnCall(i int, result1 backoff.RetryOption) {
	fake.withMaxElapsedTimeMutex.Lock()
	defer fake.withMaxElapsedTimeMutex.Unlock()
	fake.WithMaxElapsedTimeStub = nil
	if fake.withMaxElapsedTimeReturnsOnCall == nil {
		fake.withMaxElapsedTimeReturnsOnCall = make(map[int]struct {
			result1 backoff.RetryOption
		})
	}
	fake.withMaxElapsedTimeReturnsOnCall[i] = struct {
		result1 backoff.RetryOption
	}{result1}
}

func (fake *FakeBackOffFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBackOffFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ retryhttp.BackOffFactory = new(FakeBackOffFactory)
