// Code generated by counterfeiter. DO NOT EDIT.
package retryhttpfakes

import (
	"sync"
	"time"

	"github.com/concourse/retryhttp"
)

type FakeBackOff struct {
	NextBackOffStub        func() time.Duration
	nextBackOffMutex       sync.RWMutex
	nextBackOffArgsForCall []struct {
	}
	nextBackOffReturns struct {
		result1 time.Duration
	}
	nextBackOffReturnsOnCall map[int]struct {
		result1 time.Duration
	}
	ResetStub        func()
	resetMutex       sync.RWMutex
	resetArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBackOff) NextBackOff() time.Duration {
	fake.nextBackOffMutex.Lock()
	ret, specificReturn := fake.nextBackOffReturnsOnCall[len(fake.nextBackOffArgsForCall)]
	fake.nextBackOffArgsForCall = append(fake.nextBackOffArgsForCall, struct {
	}{})
	stub := fake.NextBackOffStub
	fakeReturns := fake.nextBackOffReturns
	fake.recordInvocation("NextBackOff", []interface{}{})
	fake.nextBackOffMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBackOff) NextBackOffCallCount() int {
	fake.nextBackOffMutex.RLock()
	defer fake.nextBackOffMutex.RUnlock()
	return len(fake.nextBackOffArgsForCall)
}

func (fake *FakeBackOff) NextBackOffCalls(stub func() time.Duration) {
	fake.nextBackOffMutex.Lock()
	defer fake.nextBackOffMutex.Unlock()
	fake.NextBackOffStub = stub
}

func (fake *FakeBackOff) NextBackOffReturns(result1 time.Duration) {
	fake.nextBackOffMutex.Lock()
	defer fake.nextBackOffMutex.Unlock()
	fake.NextBackOffStub = nil
	fake.nextBackOffReturns = struct {
		result1 time.Duration
	}{result1}
}

func (fake *FakeBackOff) NextBackOffReturnsOnCall(i int, result1 time.Duration) {
	fake.nextBackOffMutex.Lock()
	defer fake.nextBackOffMutex.Unlock()
	fake.NextBackOffStub = nil
	if fake.nextBackOffReturnsOnCall == nil {
		fake.nextBackOffReturnsOnCall = make(map[int]struct {
			result1 time.Duration
		})
	}
	fake.nextBackOffReturnsOnCall[i] = struct {
		result1 time.Duration
	}{result1}
}

func (fake *FakeBackOff) Reset() {
	fake.resetMutex.Lock()
	fake.resetArgsForCall = append(fake.resetArgsForCall, struct {
	}{})
	stub := fake.ResetStub
	fake.recordInvocation("Reset", []interface{}{})
	fake.resetMutex.Unlock()
	if stub != nil {
		fake.ResetStub()
	}
}

func (fake *FakeBackOff) ResetCallCount() int {
	fake.resetMutex.RLock()
	defer fake.resetMutex.RUnlock()
	return len(fake.resetArgsForCall)
}

func (fake *FakeBackOff) ResetCalls(stub func()) {
	fake.resetMutex.Lock()
	defer fake.resetMutex.Unlock()
	fake.ResetStub = stub
}

func (fake *FakeBackOff) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBackOff) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ retryhttp.BackOff = new(FakeBackOff)
