// Code generated by counterfeiter. DO NOT EDIT.
package retryhttpfakes

import (
	"bufio"
	"net"
	"sync"

	"github.com/concourse/retryhttp"
)

type FakeDoHijackCloserFactory struct {
	NewDoHijackCloserStub        func(net.Conn, *bufio.Reader) retryhttp.DoHijackCloser
	newDoHijackCloserMutex       sync.RWMutex
	newDoHijackCloserArgsForCall []struct {
		arg1 net.Conn
		arg2 *bufio.Reader
	}
	newDoHijackCloserReturns struct {
		result1 retryhttp.DoHijackCloser
	}
	newDoHijackCloserReturnsOnCall map[int]struct {
		result1 retryhttp.DoHijackCloser
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDoHijackCloserFactory) NewDoHijackCloser(arg1 net.Conn, arg2 *bufio.Reader) retryhttp.DoHijackCloser {
	fake.newDoHijackCloserMutex.Lock()
	ret, specificReturn := fake.newDoHijackCloserReturnsOnCall[len(fake.newDoHijackCloserArgsForCall)]
	fake.newDoHijackCloserArgsForCall = append(fake.newDoHijackCloserArgsForCall, struct {
		arg1 net.Conn
		arg2 *bufio.Reader
	}{arg1, arg2})
	stub := fake.NewDoHijackCloserStub
	fakeReturns := fake.newDoHijackCloserReturns
	fake.recordInvocation("NewDoHijackCloser", []interface{}{arg1, arg2})
	fake.newDoHijackCloserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDoHijackCloserFactory) NewDoHijackCloserCallCount() int {
	fake.newDoHijackCloserMutex.RLock()
	defer fake.newDoHijackCloserMutex.RUnlock()
	return len(fake.newDoHijackCloserArgsForCall)
}

func (fake *FakeDoHijackCloserFactory) NewDoHijackCloserCalls(stub func(net.Conn, *bufio.Reader) retryhttp.DoHijackCloser) {
	fake.newDoHijackCloserMutex.Lock()
	defer fake.newDoHijackCloserMutex.Unlock()
	fake.NewDoHijackCloserStub = stub
}

func (fake *FakeDoHijackCloserFactory) NewDoHijackCloserArgsForCall(i int) (net.Conn, *bufio.Reader) {
	fake.newDoHijackCloserMutex.RLock()
	defer fake.newDoHijackCloserMutex.RUnlock()
	argsForCall := fake.newDoHijackCloserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDoHijackCloserFactory) NewDoHijackCloserReturns(result1 retryhttp.DoHijackCloser) {
	fake.newDoHijackCloserMutex.Lock()
	defer fake.newDoHijackCloserMutex.Unlock()
	fake.NewDoHijackCloserStub = nil
	fake.newDoHijackCloserReturns = struct {
		result1 retryhttp.DoHijackCloser
	}{result1}
}

func (fake *FakeDoHijackCloserFactory) NewDoHijackCloserReturnsOnCall(i int, result1 retryhttp.DoHijackCloser) {
	fake.newDoHijackCloserMutex.Lock()
	defer fake.newDoHijackCloserMutex.Unlock()
	fake.NewDoHijackCloserStub = nil
	if fake.newDoHijackCloserReturnsOnCall == nil {
		fake.newDoHijackCloserReturnsOnCall = make(map[int]struct {
			result1 retryhttp.DoHijackCloser
		})
	}
	fake.newDoHijackCloserReturnsOnCall[i] = struct {
		result1 retryhttp.DoHijackCloser
	}{result1}
}

func (fake *FakeDoHijackCloserFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDoHijackCloserFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ retryhttp.DoHijackCloserFactory = new(FakeDoHijackCloserFactory)
