// Code generated by counterfeiter. DO NOT EDIT.
package retryhttpfakes

import (
	"sync"

	"github.com/concourse/retryhttp"
)

type FakeRetryer struct {
	IsRetryableStub        func(error) bool
	isRetryableMutex       sync.RWMutex
	isRetryableArgsForCall []struct {
		arg1 error
	}
	isRetryableReturns struct {
		result1 bool
	}
	isRetryableReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRetryer) IsRetryable(arg1 error) bool {
	fake.isRetryableMutex.Lock()
	ret, specificReturn := fake.isRetryableReturnsOnCall[len(fake.isRetryableArgsForCall)]
	fake.isRetryableArgsForCall = append(fake.isRetryableArgsForCall, struct {
		arg1 error
	}{arg1})
	stub := fake.IsRetryableStub
	fakeReturns := fake.isRetryableReturns
	fake.recordInvocation("IsRetryable", []interface{}{arg1})
	fake.isRetryableMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRetryer) IsRetryableCallCount() int {
	fake.isRetryableMutex.RLock()
	defer fake.isRetryableMutex.RUnlock()
	return len(fake.isRetryableArgsForCall)
}

func (fake *FakeRetryer) IsRetryableCalls(stub func(error) bool) {
	fake.isRetryableMutex.Lock()
	defer fake.isRetryableMutex.Unlock()
	fake.IsRetryableStub = stub
}

func (fake *FakeRetryer) IsRetryableArgsForCall(i int) error {
	fake.isRetryableMutex.RLock()
	defer fake.isRetryableMutex.RUnlock()
	argsForCall := fake.isRetryableArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRetryer) IsRetryableReturns(result1 bool) {
	fake.isRetryableMutex.Lock()
	defer fake.isRetryableMutex.Unlock()
	fake.IsRetryableStub = nil
	fake.isRetryableReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeRetryer) IsRetryableReturnsOnCall(i int, result1 bool) {
	fake.isRetryableMutex.Lock()
	defer fake.isRetryableMutex.Unlock()
	fake.IsRetryableStub = nil
	if fake.isRetryableReturnsOnCall == nil {
		fake.isRetryableReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isRetryableReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeRetryer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRetryer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ retryhttp.Retryer = new(FakeRetryer)
